services:
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    ports:
      - 7878:7878
    volumes:
      - ./radarr:/config
      - /[YourPathHere]:/data
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    ports:
      - 8989:8989
    volumes:
      - ./sonarr:/config
      - /[YourPathHere]:/data
    restart: unless-stopped

  readarr:
    image: lscr.io/linuxserver/readarr:latest
    container_name: readarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    ports:
      - 8787:8787
    volumes:
      - ./readarr:/config
      - /[YourPathHere]:/data
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    ports:
      - 9696:9696
    volumes:
      - ./prowlarr:/config
    restart: unless-stopped
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Toronto
    volumes:
      - ./lidarr:/config
      - /[YourPathHere]:/data
    ports:
      - 8686:8686
    restart: unless-stopped
